package com.yougou;

import java.util.Date;

public class TaobaoOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.ID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.ORDER_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.TID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.ALIPAY_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String alipayNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.SELLER_ID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.INVOICE_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String invoiceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.PAYMENT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.NUM
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.DISCOUNT_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double discountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.TOTAL_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.POST_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double postFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.BUYER_EMAIL
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String buyerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.BUYER_MESSAGE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String buyerMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.BUYER_NICK
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_ADDRESS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_CITY
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_DISTRICT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_MOBILE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_PHONE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_STATE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.RECEIVER_ZIP
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String receiverZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.CONSIGN_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date consignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.CREATED
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.MODIFIED
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.SYNC_STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String syncStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.SYNC_BATCH_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String syncBatchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.CREATE_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.UPDATE_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.SYNC_REMARK
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String syncRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.SELLER_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String sellerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.END_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.COD
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String cod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.TYPE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.LOGISTICS_COMPANY_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String logisticsCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.LOGISTICS_COMPANY_CODE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String logisticsCompanyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.OUT_SID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String outSid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.ADJUST_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double adjustFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.SHIPPING_TYPE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String shippingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.IS_BRAND_SALE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double isBrandSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.IS_PRESELL
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String isPresell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.PRESELL_STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private String presellStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.FRONT_MONEY
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double frontMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.FINAL_PAYMENT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Double finalPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.FRONT_MONEY_PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date frontMoneyPayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_order.FINAL_PAYMENT_PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    private Date finalPaymentPayTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.ID
     *
     * @return the value of taobao_order.ID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.ID
     *
     * @param id the value for taobao_order.ID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.ORDER_NO
     *
     * @return the value of taobao_order.ORDER_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.ORDER_NO
     *
     * @param orderNo the value for taobao_order.ORDER_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.TID
     *
     * @return the value of taobao_order.TID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.TID
     *
     * @param tid the value for taobao_order.TID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.ALIPAY_NO
     *
     * @return the value of taobao_order.ALIPAY_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getAlipayNo() {
        return alipayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.ALIPAY_NO
     *
     * @param alipayNo the value for taobao_order.ALIPAY_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setAlipayNo(String alipayNo) {
        this.alipayNo = alipayNo == null ? null : alipayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.SELLER_ID
     *
     * @return the value of taobao_order.SELLER_ID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.SELLER_ID
     *
     * @param sellerId the value for taobao_order.SELLER_ID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.INVOICE_NAME
     *
     * @return the value of taobao_order.INVOICE_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getInvoiceName() {
        return invoiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.INVOICE_NAME
     *
     * @param invoiceName the value for taobao_order.INVOICE_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setInvoiceName(String invoiceName) {
        this.invoiceName = invoiceName == null ? null : invoiceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.PAY_TIME
     *
     * @return the value of taobao_order.PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.PAY_TIME
     *
     * @param payTime the value for taobao_order.PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.PAYMENT
     *
     * @return the value of taobao_order.PAYMENT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.PAYMENT
     *
     * @param payment the value for taobao_order.PAYMENT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setPayment(Double payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.NUM
     *
     * @return the value of taobao_order.NUM
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.NUM
     *
     * @param num the value for taobao_order.NUM
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.DISCOUNT_FEE
     *
     * @return the value of taobao_order.DISCOUNT_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.DISCOUNT_FEE
     *
     * @param discountFee the value for taobao_order.DISCOUNT_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setDiscountFee(Double discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.TOTAL_FEE
     *
     * @return the value of taobao_order.TOTAL_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.TOTAL_FEE
     *
     * @param totalFee the value for taobao_order.TOTAL_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.POST_FEE
     *
     * @return the value of taobao_order.POST_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.POST_FEE
     *
     * @param postFee the value for taobao_order.POST_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setPostFee(Double postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.STATUS
     *
     * @return the value of taobao_order.STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.STATUS
     *
     * @param status the value for taobao_order.STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.BUYER_EMAIL
     *
     * @return the value of taobao_order.BUYER_EMAIL
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.BUYER_EMAIL
     *
     * @param buyerEmail the value for taobao_order.BUYER_EMAIL
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.BUYER_MESSAGE
     *
     * @return the value of taobao_order.BUYER_MESSAGE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getBuyerMessage() {
        return buyerMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.BUYER_MESSAGE
     *
     * @param buyerMessage the value for taobao_order.BUYER_MESSAGE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setBuyerMessage(String buyerMessage) {
        this.buyerMessage = buyerMessage == null ? null : buyerMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.BUYER_NICK
     *
     * @return the value of taobao_order.BUYER_NICK
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.BUYER_NICK
     *
     * @param buyerNick the value for taobao_order.BUYER_NICK
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_ADDRESS
     *
     * @return the value of taobao_order.RECEIVER_ADDRESS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_ADDRESS
     *
     * @param receiverAddress the value for taobao_order.RECEIVER_ADDRESS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_CITY
     *
     * @return the value of taobao_order.RECEIVER_CITY
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_CITY
     *
     * @param receiverCity the value for taobao_order.RECEIVER_CITY
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_DISTRICT
     *
     * @return the value of taobao_order.RECEIVER_DISTRICT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_DISTRICT
     *
     * @param receiverDistrict the value for taobao_order.RECEIVER_DISTRICT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_MOBILE
     *
     * @return the value of taobao_order.RECEIVER_MOBILE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_MOBILE
     *
     * @param receiverMobile the value for taobao_order.RECEIVER_MOBILE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_NAME
     *
     * @return the value of taobao_order.RECEIVER_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_NAME
     *
     * @param receiverName the value for taobao_order.RECEIVER_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_PHONE
     *
     * @return the value of taobao_order.RECEIVER_PHONE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_PHONE
     *
     * @param receiverPhone the value for taobao_order.RECEIVER_PHONE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_STATE
     *
     * @return the value of taobao_order.RECEIVER_STATE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_STATE
     *
     * @param receiverState the value for taobao_order.RECEIVER_STATE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.RECEIVER_ZIP
     *
     * @return the value of taobao_order.RECEIVER_ZIP
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.RECEIVER_ZIP
     *
     * @param receiverZip the value for taobao_order.RECEIVER_ZIP
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.CONSIGN_TIME
     *
     * @return the value of taobao_order.CONSIGN_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getConsignTime() {
        return consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.CONSIGN_TIME
     *
     * @param consignTime the value for taobao_order.CONSIGN_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setConsignTime(Date consignTime) {
        this.consignTime = consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.CREATED
     *
     * @return the value of taobao_order.CREATED
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.CREATED
     *
     * @param created the value for taobao_order.CREATED
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.MODIFIED
     *
     * @return the value of taobao_order.MODIFIED
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.MODIFIED
     *
     * @param modified the value for taobao_order.MODIFIED
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.SYNC_STATUS
     *
     * @return the value of taobao_order.SYNC_STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getSyncStatus() {
        return syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.SYNC_STATUS
     *
     * @param syncStatus the value for taobao_order.SYNC_STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus == null ? null : syncStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.SYNC_BATCH_NO
     *
     * @return the value of taobao_order.SYNC_BATCH_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getSyncBatchNo() {
        return syncBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.SYNC_BATCH_NO
     *
     * @param syncBatchNo the value for taobao_order.SYNC_BATCH_NO
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setSyncBatchNo(String syncBatchNo) {
        this.syncBatchNo = syncBatchNo == null ? null : syncBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.CREATE_TIME
     *
     * @return the value of taobao_order.CREATE_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.CREATE_TIME
     *
     * @param createTime the value for taobao_order.CREATE_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.UPDATE_TIME
     *
     * @return the value of taobao_order.UPDATE_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.UPDATE_TIME
     *
     * @param updateTime the value for taobao_order.UPDATE_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.SYNC_REMARK
     *
     * @return the value of taobao_order.SYNC_REMARK
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getSyncRemark() {
        return syncRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.SYNC_REMARK
     *
     * @param syncRemark the value for taobao_order.SYNC_REMARK
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setSyncRemark(String syncRemark) {
        this.syncRemark = syncRemark == null ? null : syncRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.SELLER_NAME
     *
     * @return the value of taobao_order.SELLER_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.SELLER_NAME
     *
     * @param sellerName the value for taobao_order.SELLER_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.END_TIME
     *
     * @return the value of taobao_order.END_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.END_TIME
     *
     * @param endTime the value for taobao_order.END_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.COD
     *
     * @return the value of taobao_order.COD
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getCod() {
        return cod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.COD
     *
     * @param cod the value for taobao_order.COD
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setCod(String cod) {
        this.cod = cod == null ? null : cod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.TYPE
     *
     * @return the value of taobao_order.TYPE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.TYPE
     *
     * @param type the value for taobao_order.TYPE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.LOGISTICS_COMPANY_NAME
     *
     * @return the value of taobao_order.LOGISTICS_COMPANY_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getLogisticsCompanyName() {
        return logisticsCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.LOGISTICS_COMPANY_NAME
     *
     * @param logisticsCompanyName the value for taobao_order.LOGISTICS_COMPANY_NAME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setLogisticsCompanyName(String logisticsCompanyName) {
        this.logisticsCompanyName = logisticsCompanyName == null ? null : logisticsCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.LOGISTICS_COMPANY_CODE
     *
     * @return the value of taobao_order.LOGISTICS_COMPANY_CODE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getLogisticsCompanyCode() {
        return logisticsCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.LOGISTICS_COMPANY_CODE
     *
     * @param logisticsCompanyCode the value for taobao_order.LOGISTICS_COMPANY_CODE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setLogisticsCompanyCode(String logisticsCompanyCode) {
        this.logisticsCompanyCode = logisticsCompanyCode == null ? null : logisticsCompanyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.OUT_SID
     *
     * @return the value of taobao_order.OUT_SID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getOutSid() {
        return outSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.OUT_SID
     *
     * @param outSid the value for taobao_order.OUT_SID
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setOutSid(String outSid) {
        this.outSid = outSid == null ? null : outSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.ADJUST_FEE
     *
     * @return the value of taobao_order.ADJUST_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getAdjustFee() {
        return adjustFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.ADJUST_FEE
     *
     * @param adjustFee the value for taobao_order.ADJUST_FEE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setAdjustFee(Double adjustFee) {
        this.adjustFee = adjustFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.SHIPPING_TYPE
     *
     * @return the value of taobao_order.SHIPPING_TYPE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getShippingType() {
        return shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.SHIPPING_TYPE
     *
     * @param shippingType the value for taobao_order.SHIPPING_TYPE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setShippingType(String shippingType) {
        this.shippingType = shippingType == null ? null : shippingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.IS_BRAND_SALE
     *
     * @return the value of taobao_order.IS_BRAND_SALE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getIsBrandSale() {
        return isBrandSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.IS_BRAND_SALE
     *
     * @param isBrandSale the value for taobao_order.IS_BRAND_SALE
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setIsBrandSale(Double isBrandSale) {
        this.isBrandSale = isBrandSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.IS_PRESELL
     *
     * @return the value of taobao_order.IS_PRESELL
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getIsPresell() {
        return isPresell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.IS_PRESELL
     *
     * @param isPresell the value for taobao_order.IS_PRESELL
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setIsPresell(String isPresell) {
        this.isPresell = isPresell == null ? null : isPresell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.PRESELL_STATUS
     *
     * @return the value of taobao_order.PRESELL_STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public String getPresellStatus() {
        return presellStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.PRESELL_STATUS
     *
     * @param presellStatus the value for taobao_order.PRESELL_STATUS
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setPresellStatus(String presellStatus) {
        this.presellStatus = presellStatus == null ? null : presellStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.FRONT_MONEY
     *
     * @return the value of taobao_order.FRONT_MONEY
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getFrontMoney() {
        return frontMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.FRONT_MONEY
     *
     * @param frontMoney the value for taobao_order.FRONT_MONEY
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setFrontMoney(Double frontMoney) {
        this.frontMoney = frontMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.FINAL_PAYMENT
     *
     * @return the value of taobao_order.FINAL_PAYMENT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Double getFinalPayment() {
        return finalPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.FINAL_PAYMENT
     *
     * @param finalPayment the value for taobao_order.FINAL_PAYMENT
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setFinalPayment(Double finalPayment) {
        this.finalPayment = finalPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.FRONT_MONEY_PAY_TIME
     *
     * @return the value of taobao_order.FRONT_MONEY_PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getFrontMoneyPayTime() {
        return frontMoneyPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.FRONT_MONEY_PAY_TIME
     *
     * @param frontMoneyPayTime the value for taobao_order.FRONT_MONEY_PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setFrontMoneyPayTime(Date frontMoneyPayTime) {
        this.frontMoneyPayTime = frontMoneyPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_order.FINAL_PAYMENT_PAY_TIME
     *
     * @return the value of taobao_order.FINAL_PAYMENT_PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public Date getFinalPaymentPayTime() {
        return finalPaymentPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_order.FINAL_PAYMENT_PAY_TIME
     *
     * @param finalPaymentPayTime the value for taobao_order.FINAL_PAYMENT_PAY_TIME
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    public void setFinalPaymentPayTime(Date finalPaymentPayTime) {
        this.finalPaymentPayTime = finalPaymentPayTime;
    }
}