package com.yougou;

import com.yougou.TaobaoOrder;
import java.util.List;

public interface TaobaoOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_order
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    int insert(TaobaoOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_order
     *
     * @mbg.generated Tue Dec 12 14:07:52 CST 2017
     */
    List<TaobaoOrder> selectAll();
}